djangoProject1/urls.py
# from django.contrib import admin
from django.urls import path
from web.views import account, level, customer, policy, my_order, my_transaction, my_space

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('/', account.index, name='index'),

    path('login/', account.login, name='login'),
    path('logout/', account.logout, name='logout'),
    path('sms_send/', account.sms_send, name='sms_send'),

    path('home/', account.home, name='home'),

    path('level/', level.level, name='level'),
    path('level/add/', level.level_add, name='level_add'),
    path('level/edit/<int:pk>/', level.level_edit, name='level_edit'),
    path('level/delete/', level.level_delete, name='level_delete'),

    path('customer/', customer.customer, name='customer'),
    path('customer/add/', customer.customer_add, name="customer_add"),
    path('customer/edit/<int:pk>/', customer.customer_edit, name="customer_edit"),
    path('customer/reset/<int:pk>/', customer.customer_reset, name="customer_reset"),
    path('customer/delete/', customer.customer_delete, name="customer_delete"),
    path('customer/charge/<int:pk>/', customer.customer_change, name="customer_change"),
    path('customer/add_charge/<int:pk>/', customer.customer_add_change, name="customer_add_change"),

    path('policy/', policy.policy, name="policy"),
    path('policy/add/', policy.policy_add, name="policy_add"),
    path('policy/edit/<int:pk>/', policy.policy_edit, name="policy_edit"),
    path('policy/delete/', policy.policy_delete, name="policy_delete"),

    path('my_order/', my_order.my_order, name="my_order"),
    path('my_order/add/', my_order.my_order_add, name="my_order_add"),
    path('my_order/cancel/<int:pk>/', my_order.my_order_cancel, name="my_order_cancel"),

    path('my_transaction/', my_transaction.my_transaction, name="my_transaction"),
    path('transaction/', my_transaction.transaction, name="transaction"),

    path('my_space/', my_space.my_space, name='my_space')
]

web/urls.py
from django.urls import path
# from . import views
#
# urlpatterns = [
#     path('', views.login, name="login"),
# ]

web/models.py
from django.db import models


class ActiveBaseModel(models.Model):
    active = models.SmallIntegerField(verbose_name="状态", default=1, choices=((1, "激活"), (0, "删除"),))

    class Meta:
        abstract = True


class Administrator(ActiveBaseModel):
    """ 管理员表 """
    username = models.CharField(verbose_name="用户名", max_length=32, db_index=True)
    password = models.CharField(verbose_name="密码", max_length=64)
    mobile = models.CharField(verbose_name="手机号", max_length=11, db_index=True)
    create_date = models.DateTimeField(verbose_name="创建日期", auto_now_add=True)


class Level(ActiveBaseModel):
    """ 级别表 """
    title = models.CharField(verbose_name="级别", max_length=32)
    percent = models.IntegerField(verbose_name="折扣")

    def __str__(self):
        return self.title


class Customer(ActiveBaseModel):
    """ 客户表 """
    username = models.CharField(verbose_name="用户名", max_length=32, db_index=True)
    password = models.CharField(verbose_name="密码", max_length=64)
    mobile = models.CharField(verbose_name="手机号", max_length=11, db_index=True)
    balance = models.DecimalField(verbose_name="账户余额", default=0, max_digits=10, decimal_places=2)
    level = models.ForeignKey(verbose_name="级别", to="Level", on_delete=models.CASCADE)
    create_date = models.DateTimeField(verbose_name="创建日期", auto_now_add=True)
    creator = models.ForeignKey(verbose_name="创建者", to="Administrator", on_delete=models.CASCADE)


class PricePolicy(models.Model):
    """ 价格策略（原价，后续可以根据用级别不同做不同折扣）
    1  1000 10
    2  2000 18
    """
    count = models.IntegerField(verbose_name="数量")
    price = models.DecimalField(verbose_name="价格", default=0, max_digits=10, decimal_places=2)


class Order(ActiveBaseModel):
    """ 订单表 """
    status_choices = (
        (1, "待执行"),
        (2, "正在执行"),
        (3, "已完成"),
        (4, "失败"),
        (5, "已撤单")
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)

    # 202211022123123123
    oid = models.CharField(verbose_name="订单号", max_length=64, unique=True)
    url = models.URLField(verbose_name="视频地址", db_index=True)
    count = models.IntegerField(verbose_name="数量")

    price = models.DecimalField(verbose_name="价格", default=0, max_digits=10, decimal_places=2)
    real_price = models.DecimalField(verbose_name="实际价格", default=0, max_digits=10, decimal_places=2)

    old_view_count = models.CharField(verbose_name="原播放量", max_length=32, default="0")

    create_datetime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    customer = models.ForeignKey(verbose_name="客户", to="Customer", on_delete=models.CASCADE)
    memo = models.TextField(verbose_name="备注", null=True, blank=True)


class TransactionRecord(ActiveBaseModel):
    """ 交易记录 """
    charge_type_class_mapping = {
        1: "success",
        2: "danger",
        3: "default",
        4: "info",
        5: "primary",
    }
    charge_type_choices = ((1, "充值"), (2, "扣款"), (3, "创建订单"), (4, "删除订单"), (5, "撤单"),)
    charge_type = models.SmallIntegerField(verbose_name="类型", choices=charge_type_choices)

    customer = models.ForeignKey(verbose_name="客户", to="Customer", on_delete=models.CASCADE)
    amount = models.DecimalField(verbose_name="金额", default=0, max_digits=10, decimal_places=2)

    creator = models.ForeignKey(verbose_name="管理员", to="Administrator", on_delete=models.CASCADE, null=True, blank=True)

    order_oid = models.CharField(verbose_name="订单号", max_length=64, null=True, blank=True, db_index=True)
    create_datetime = models.DateTimeField(verbose_name="交易时间", auto_now_add=True)
    memo = models.TextField(verbose_name="备注", null=True, blank=True)

web/views/customer.py
from django.shortcuts import render, redirect
from django.db.models import Q

from django import forms
from utils.bootstrap import BootStrapForm
from web import models
from web.forms.forms import CustomerModelForm, CustomerEditModelForm, CustomerResetModelForm
from utils.response import BaseResponse
from django.http import JsonResponse
from utils.pager import Pagination


def customer(request):
    keyword = request.GET.get('keyword', '').strip()
    con = Q()
    if keyword:
        con.connector = 'OR'
        con.children.append(('username__contains', keyword))
        con.children.append(('mobile__contains', keyword))
        con.children.append(('level__title__contains', keyword))

    queryset = models.Customer.objects.filter(con).filter(active=1).select_related('level')
    obj = Pagination(request, queryset)
    context = {
        "queryset": queryset[obj.start:obj.end],
        "pager_string": obj.html(),
        "keyword": keyword
    }

    return render(request, 'web/customer.html', context)


def customer_add(request):
    if request.method == "GET":
        form = CustomerModelForm(request)
        return render(request, "web/data_form.html", {'form': form})

    form = CustomerModelForm(request, data=request.POST)
    if not form.is_valid():
        return render(request, "web/data_form.html", {'form': form})

    form.instance.creator_id = request.user_data.user_id
    form.save()
    return redirect("/customer/")


def customer_edit(request, pk):
    instance = models.Customer.objects.filter(id=pk, active=1).first()

    if request.method == 'GET':
        form = CustomerEditModelForm(request, instance=instance)
        return render(request, 'web/data_form.html', {'form': form})

    form = CustomerEditModelForm(request, instance=instance, data=request.POST)
    if not form.is_valid():
        return render(request, 'web/data_form.html', {'form': form})
    form.save()

    from utils.link import filter_reverse
    return redirect(filter_reverse(request, "/customer/"))


def customer_reset(request, pk):
    if request.method == "GET":
        form = CustomerResetModelForm()
        return render(request, 'web/data_form.html', {'form': form})
    instance = models.Customer.objects.filter(id=pk, active=1).first()
    form = CustomerResetModelForm(data=request.POST, instance=instance)
    if not form.is_valid():
        return render(request, 'web/data_form.html', {'form': form})
    form.save()
    return redirect("/customer/")


def customer_delete(request):
    cid = request.GET.get('cid', 0)
    if not cid:
        res = BaseResponse(status=False, detail="请选择要删除的数据")
        return JsonResponse(res.dict)

    exists = models.Customer.objects.filter(id=cid, active=1).exists()
    if not exists:
        res = BaseResponse(status=False, detail="要删除的数据不存在")
        return JsonResponse(res.dict)

    models.Customer.objects.filter(id=cid, active=1).update(active=0)
    res = BaseResponse(status=True)
    return JsonResponse(res.dict)


class ChargeModelForm(BootStrapForm, forms.ModelForm):
    # 静态变量
    charge_type = forms.TypedChoiceField(
        label="类型",
        choices=[(1, "充值"), (2, "扣款")],  # 只适合固定的数据，不适合去数据表中数据
        coerce=int
    )

    class Meta:
        model = models.TransactionRecord
        fields = ['charge_type', 'amount']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # self.fields['charge_type'].choices = [(1, "充值"), (2, "扣款")]  # 只适合固定的数据，不适合去数据表中数据
        # self.fields['creator'].choices = models.Administrator.objects.filter(id__gt=1).values_list("id", 'username')


def customer_change(request, pk):
    """ 交易记录列表 """

    queryset = models.TransactionRecord.objects.filter(customer_id=pk, customer__active=1, active=1).select_related(
        'customer').order_by('-id')
    pager = Pagination(request, queryset)

    form = ChargeModelForm()
    # return render(request, 'customer_change.html', {"pager": pager, "form": form, 'pk': pk})
    return render(request, 'web/customer_charge.html', locals())


def customer_add_change(reqeust, pk):
    form = ChargeModelForm(data=reqeust.POST)
    if not form.is_valid():
        return JsonResponse({'status': False, 'detail': form.errors})

    # 如果校验成功
    amount = form.cleaned_data['amount']
    charge_type = form.cleaned_data['charge_type']
    from django.db import transaction
    try:
        with transaction.atomic():
            # 1.对当前操作的客户进行更新操作，账户余额：增加、减少 + 锁
            cus_object = models.Customer.objects.filter(id=pk, active=1).select_for_update().first()

            if charge_type == 2 and cus_object.balance < amount:
                return JsonResponse(
                    {'status': False, 'detail': {"amount": ["余额不足，账户总余额只有:{}".format(cus_object.balance)]}})

            if charge_type == 1:
                cus_object.balance = cus_object.balance + amount
            else:
                cus_object.balance = cus_object.balance - amount
            cus_object.save()

            # 2.交易记录
            form.instance.customer = cus_object
            form.instance.creator_id = reqeust.user_data.user_id
            form.save()

    except Exception as e:
        print(e)
        return JsonResponse({'status': False, 'detail': {"amount": ["操作失败1"]}})

    return JsonResponse({'status': True})

web/views/level.py
from django.shortcuts import render, redirect
from web import models
from django.urls import reverse
from web.forms.forms import LevelModelForm


def level(request):
    queryset = models.Level.objects.filter(active=1).order_by('-percent')
    return render(request, 'web/level.html', {"queryset": queryset})


def level_add(request):
    if request.method == "GET":
        form = LevelModelForm()
        return render(request, 'web/data_form.html', {"form": form})

    form = LevelModelForm(data=request.POST)
    if not form.is_valid():
        return render(request, 'web/data_form.html', {"form": form})
    all_title = models.Level.objects.filter(active=1).values_list('title', flat=True)
    title = form.cleaned_data['title']
    if title in all_title:
        form.add_error('title', "该级别已存在")
        return render(request, 'web/data_form.html', {"form": form})
    form.save()
    return redirect(reverse('level'))


def level_edit(request, pk):
    level_object = models.Level.objects.filter(id=pk, active=1).first()

    if request.method == "GET":
        form = LevelModelForm(instance=level_object)
        return render(request, 'web/data_form.html', {"form": form})

    form = LevelModelForm(data=request.POST, instance=level_object)
    if not form.is_valid():
        return render(request, 'web/data_form.html', {"form": form})

    form.save()
    return redirect(reverse('level'))


def level_delete(request):
    cid = request.GET.get('cid', 0)
    exists = models.Customer.objects.filter(level_id=cid).exists()
    if not exists:
        models.Level.objects.filter(id=cid).update(active=0)
    return redirect(reverse('level'))

web/views/my_space.py
from web import models
from django.shortcuts import render
from django import forms


# class CustomerForm(forms.ModelForm):
#     class Meta:
#         model = models.Customer
#         exclude = ['active', 'password']
#
#     def __init__(self, *args, **kwargs):
#         super(CustomerForm, self).__init__(*args, **kwargs)
#         # 设置所有字段为只读
#         for field in self.fields.values():
#             field.widget.attrs['readonly'] = True
#         self.fields['create_date'] = forms.DateTimeField(
#             label="注册日期",
#             initial=self.instance.create_date)


def my_space(request):
    query = models.Customer.objects.filter(id=request.user_data.user_id).select_related('level', 'creator')
    return render(request, 'web/my_space.html', {'query': query})

web/views/my_transaction.py
from django.shortcuts import render
from web import models
from utils.pager import Pagination
from django.db.models import Q
from utils.group import Option, NbSearchGroup


def my_transaction(request):
    """ 我的交易记录 """
    # 第一步：配置和传参
    search_group = NbSearchGroup(
        request,
        models.TransactionRecord,
        Option('charge_type'),  # choice
    )

    keyword = request.GET.get("keyword", "").strip()
    con = Q()
    if keyword:
        con.connector = 'OR'
        con.children.append(('order_oid__contains', keyword))

    # 第二步：获取条件 .filter(**search_group.get_condition)
    queryset = models.TransactionRecord.objects.filter(con).filter(**search_group.get_condition).filter(
        customer_id=request.user_data.user_id,
        active=1).order_by(
        "-id")
    pager = Pagination(request, queryset)

    context = {
        "pager": pager,
        "keyword": keyword,
        "search_group": search_group  # 第三步：传入前端页面
    }
    return render(request, 'web/my_transaction.html', context)


def transaction(request):
    # 第一步：配置和传参
    search_group = NbSearchGroup(
        request,
        models.TransactionRecord,
        Option('charge_type'),  # choice
    )

    keyword = request.GET.get("keyword", "").strip()
    con = Q()
    if keyword:
        con.connector = 'OR'
        con.children.append(('order_oid__contains', keyword))
        con.children.append(('customer__username__contains', keyword))

    # 第二步：获取条件 .filter(**search_group.get_condition)
    queryset = models.TransactionRecord.objects.filter(con).filter(**search_group.get_condition).filter(
        active=1).order_by("-id")
    pager = Pagination(request, queryset)

    context = {
        "pager": pager,
        "keyword": keyword,
        "search_group": search_group  # 第三步：传入前端页面
    }

    return render(request, "web/transaction.html", context)

web/views/policy.py
from django.shortcuts import render, redirect
from web import models
from utils.pager import Pagination
from django import forms
from utils.bootstrap import BootStrapForm
from utils.response import BaseResponse
from django.http import JsonResponse


def policy(request):
    queryset = models.PricePolicy.objects.all().order_by('count')
    pager = Pagination(request, queryset)
    return render(request, 'web/policy.html', {'pager': pager})


class PolicyModelForm(BootStrapForm, forms.ModelForm):
    class Meta:
        model = models.PricePolicy
        fields = "__all__"


def policy_add(request):
    if request.method == "GET":
        form = PolicyModelForm()
        return render(request, 'web/data_form.html', {'form': form})
    form = PolicyModelForm(data=request.POST)
    if not form.is_valid():
        return render(request, 'web/data_form.html', {'form': form})
    form.save()
    return redirect('/policy/')


def policy_edit(request, pk):
    instance = models.PricePolicy.objects.filter(id=pk).first()
    if request.method == "GET":
        form = PolicyModelForm(instance=instance)
        return render(request, 'web/data_form.html', {'form': form})
    form = PolicyModelForm(data=request.POST, instance=instance)
    if not form.is_valid():
        return render(request, 'web/data_form.html', {'form': form})
    form.save()
    # return redirect('/policy/list/')
    from utils.link import filter_reverse
    return redirect(filter_reverse(request, "/policy/"))


def policy_delete(request):
    res = BaseResponse(status=True)
    cid = request.GET.get('cid')
    models.PricePolicy.objects.filter(id=cid).delete()
    return JsonResponse(res.dict)

web/templates/web/customer.html
{% extends 'web/layout.html' %}
{% load static %}
{% load permission %}

{% block content %}
    <div style="margin-bottom: 10px">
        <a href="{% url 'customer_add' %}" class="btn btn-success"><i class="bi bi-plus-circle"></i> 新建</a>
        <div style="margin-left: auto;float: right">
            <form class="row g-3">
                <div class="col-auto">
                    <input name="keyword" type="text" class="form-control" placeholder="关键字查找" value="{{ keyword }}">
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-light border"><i class="bi bi-search"></i></button>
                </div>
            </form>
        </div>
    </div>
    <table class="table table-bordered my-table">
        <thead>
        <tr>
            <th>ID</th>
            <th>用户名</th>
            <th>手机号</th>
            <th>账户余额</th>
            <th>级别</th>
            <th>交易记录</th>
            <th>注册时间</th>
            <th>重置密码</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for row in queryset %}
            <tr data-row-id="{{ row.id }}">
                <td>{{ row.id }}</td>
                <td>{{ row.username }}</td>
                <td>{{ row.mobile }}</td>
                <td>{{ row.balance }}</td>
                <td>{{ row.level.title }}（{{ row.level.percent }}%）</td>
                <td>
                    <a href="{% url 'customer_change' pk=row.id %}">交易记录</a>
                </td>
                <td>{{ row.create_date|date:"Y-m-d H:i:s" }}</td>
                <td>
                    <a href="{% url 'customer_reset' pk=row.id %}">重置密码</a>
                </td>
                {% if request|has_permission:"customer_edit,customer_delete" %}
                    <td>
                        {% edit_permission request 'customer_edit' pk=row.id %}
                        {% delete_permission request 'customer_delete' pk=row.id %}
                    </td>
                {% endif %}
            </tr>
        {% endfor %}

        </tbody>
    </table>

    <div class="d-flex">
        <ul class="pagination">
            {{ pager_string }}
        </ul>
        <div style="margin-left: auto;margin-right: 50px">
            <span style="display: inline-block;">前往</span>
            <input id="inputField" type="text" class="form-control" style="width: 50px; display: inline-block;">
            <span style="display: inline-block;">页</span>
        </div>

    </div>

    {% include 'include/delete_modal.html' %}


{% endblock %}
{% block js %}
    <script>
        let DELETE_ID;
        let DELETE_URL = "{% url 'customer_delete' %}";
    </script>
    <script src="{% static 'js/delete_modal.js' %}"></script>
    <script>
        document.getElementById('inputField').addEventListener('keypress', function (event) {
            if (event.key === 'Enter') {
                let url = new URL(window.location.href);
                let params = new URLSearchParams(url.search);
                let page = $('#inputField').val()
                params.set('page', page);  // 修改或添加 'page' 参数
                url.search = params.toString();
                window.location.href = url.toString();
            }
        });
    </script>

{% endblock %}

web/templates/web/customer_charge.html
{% extends 'web/layout.html' %}
{% load static %}
{% load permission %}
{% load color %}

{% block css %}
    <style>
        .error-message {
            color: red;
            position: absolute;
        }
    </style>
{% endblock %}

{% block content %}
    <div style="margin-bottom: 5px">
        <button class="btn btn-light border-black" id="btnAdd">
            <i class="bi bi-currency-exchange"></i>修改金额
        </button>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>类型</th>
            <th>金额</th>
            <th>订单号</th>
            <th>时间</th>
            <th>其他</th>
        </tr>
        </thead>
        <tbody>
        {% for row in pager.queryset %}
            <tr>
                <td>{{ row.id }}</td>
                <td>
                    <strong class="text-{{ row.charge_type|color }} ">{{ row.get_charge_type_display }}</strong>
                </td>
                <td>{{ row.amount }}</td>
                <td>
                    {% if row.order_oid %}
                        {{ row.order_oid }}
                    {% else %}
                        -
                    {% endif %}
                </td>
                <td>{{ row.create_datetime|date:"Y-m-d H:i:s" }}</td>
                <td>
                    {% if row.memo %}
                        {{ row.memo }}
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    <ul class="pagination">
        {{ pager.html }}
    </ul>


    <div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="myModalLabel">提交数据</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" id="addForm">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label class="col-2 control-label">{{ field.label }}</label>
                                <div class="col-10" style="position: relative;margin-bottom: 25px">
                                    {{ field }}
                                    <span class="error-message">{{ field.errors.0 }}</span>
                                </div>
                            </div>
                        {% endfor %}
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="btnAddSubmit">提 交</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}



{% block js %}
    <script>
        $(function () {
            $("#btnAdd").click(function () {
                $('#addModal').modal('show');
            });

            $("#btnAddSubmit").click(function () {
                $(".error-message").empty();
                $.ajax({
                    url: "{% url 'customer_add_change' pk=pk %}",
                    type: "POST",
                    data: $("#addForm").serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            window.location.reload();
                        } else {
                            $.each(res.detail, function (k, v) {
                                $("#id_" + k).next().text(v[0]);
                            })
                        }
                    }
                })
            });
        })
    </script>
{% endblock %}

web/templates/web/data_form.html
{% extends 'web/layout.html' %}

{% block content %}
    <!-- 一行三列的form -->
    <form method="post" novalidate>
        <div id="form-container" class="row">
            {% csrf_token %}
            {% for field in form %}
                <div class="col-12">
                    <div style="margin-bottom: 20px">
                        <label for="{{ field.id_for_label }}">
                            {{ field.label }}
                            {% if field.help_text %}
                                <small>{{ field.help_text }}</small>
                            {% endif %}
                        </label>
                        {{ field }}
                        <div class="message">{{ field.errors.0 }}</div>
                    </div>
                </div>

            {% endfor %}
        </div>

        <div style="margin-top: 20px">
            <button type="submit" class="btn btn-primary">保 存</button>
        </div>
    </form>

{% endblock %}

web/templates/web/my_order.html
{% extends 'web/layout.html' %}
{% load static %}


{% block content %}
    {% if messages %}
        <div class="top-message-error">
            {% for obj in messages %}
                <div class="alert alert-{{ obj.level_tag }}">
                    {{ obj.message }}
                </div>
            {% endfor %}

        </div>
    {% endif %}

    <div style="margin-bottom: 5px">
        <a href="{% url 'my_order_add' %}" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> 创建订单
        </a>
    </div>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>订单号</th>
            <th>视频地址</th>
            <th>数量</th>
            <th>价格</th>
            <th>原播放</th>
            <th>创建时间</th>
            <th>状态</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for row in pager.queryset %}
            <tr>
                <td>{{ row.oid }}</td>
                <td>{{ row.url }}</td>
                <td>{{ row.count }}</td>
                <td>{{ row.real_price }}（{{ row.price }}）</td>
                <td>{{ row.old_view_count }}</td>
                <td>{{ row.create_datetime }}</td>
                <td>{{ row.get_status_display }}</td>
                <td>
                    {% if row.status == 1 %}
                        <a href="{% url 'my_order_cancel' pk=row.id %}" class="btn btn-danger btn-sm">撤单</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
    <ul class="pagination">
        {{ pager.html }}
    </ul>

{% endblock %}


{% block js %}
    <script>
        $(function () {
            {% if messages %}
                setTimeout(function () {
                    $(".top-message-error").hide();
                }, 5000);
                console.log("执行了")
                console.log($(".top-message-error"));

            {% endif %}
        })

    </script>
{% endblock %}

web/templates/web/my_transaction.html
{% extends 'web/layout.html' %}
{% load static %}
{% load permission %}
{% load color %}


{% block content %}

    <div style="margin-bottom: 10px" class="d-flex">
        {% include 'include/search_group.html' %}
        <div style="margin-left: auto;margin-top:30px;float: right">
            <form class="row g-3" method="get">
                <div class="col-auto">
                    <input name="keyword" type="text" class="form-control" placeholder="关键字查找" value="{{ keyword }}">
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-light border"><i class="bi bi-search"></i></button>
                </div>
            </form>
        </div>
    </div>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>类型</th>
            <th>金额</th>
            <th>订单号</th>
            <th>时间</th>
            <th>其他</th>
        </tr>
        </thead>
        <tbody>
        {% for row in pager.queryset %}
            <tr>
                <td>{{ row.id }}</td>
                <td>
                    <strong class="text-{{ row.charge_type|color }}">{{ row.get_charge_type_display }}</strong>
                </td>
                <td>
                    {{ row.amount }}
                </td>
                <td>
                    {% if row.order_oid %}
                        {{ row.order_oid }}
                    {% else %}
                        -
                    {% endif %}
                </td>
                <td>{{ row.create_datetime|date:"Y-m-d H:i:s" }}</td>
                <td>
                    {% if row.memo %}
                        {{ row.memo }}
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    <ul class="pagination">
        {{ pager.html }}
    </ul>


{% endblock %}

web/templates/web/transaction.html
{% extends 'web/layout.html' %}
{% load static %}
{% load permission %}
{% load color %}


{% block content %}

    <div style="margin-bottom: 10px" class="d-flex">
        {% include 'include/search_group.html' %}
        <div style="margin-left: auto;margin-top:30px;float: right">
            <form class="row g-3" method="get">
                <div class="col-auto">
                    <input name="keyword" type="text" class="form-control" placeholder="关键字查找" value="{{ keyword }}">
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-light border"><i class="bi bi-search"></i></button>
                </div>
            </form>
        </div>
    </div>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>类型</th>
            <th>金额</th>
            <th>客户</th>
            <th>订单号</th>
            <th>时间</th>
            <th>其他</th>
        </tr>
        </thead>
        <tbody>
        {% for row in pager.queryset %}
            <tr>
                <td>{{ row.id }}</td>
                <td>
                    <strong class="text-{{ row.charge_type|color }}">{{ row.get_charge_type_display }}</strong>
                </td>
                <td>
                    {{ row.amount }}
                </td>
                <td>
                    {{ row.customer.username }}
                </td>
                <td>
                    {% if row.order_oid %}
                        {{ row.order_oid }}
                    {% else %}
                        -
                    {% endif %}
                </td>
                <td>{{ row.create_datetime|date:"Y-m-d H:i:s" }}</td>
                <td>
                    {% if row.memo %}
                        {{ row.memo }}
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    <ul class="pagination">
        {{ pager.html }}
    </ul>


{% endblock %}